name: 自动更新

on:
  schedule:
    - cron: "45 2 * * *"
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: 登录 GitHub CLI
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: 运行程序
        run: uv run --no-dev -m src.main
        env:
          JEGOCLOUD_TOKEN: ${{ secrets.JEGOCLOUD_TOKEN }}
          JEGOCLOUD_USERNAME: ${{ secrets.JEGOCLOUD_USERNAME }}
          JEGOCLOUD_PASSWORD: ${{ secrets.JEGOCLOUD_PASSWORD }}

      - name: 删除相同标签的发行版
        continue-on-error: true
        run: gh release delete --yes --cleanup-tag result

      - name: 创建发行版
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          name: "更新服务器节点"
          tag_name: result
          files: result.json