name: 自动更新

on:
  schedule:
    - cron: "45 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  JEGOCLOUD_USERNAME: ${{ secrets.JEGOCLOUD_USERNAME }}
  JEGOCLOUD_PASSWORD: ${{ secrets.JEGOCLOUD_PASSWORD }}

jobs:
  get_modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.scan.outputs.modules }}
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7

      - name: 获取模块列表
        id: scan
        run: |
          modules=$(find ./src/proxy -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -R -s -c 'split("\n")[:-1]')
          echo "modules=$modules" >> $GITHUB_OUTPUT

  get_outbounds:
    needs: get_modules
    strategy:
      matrix:
        module: ${{ fromJson(needs.get_modules.outputs.modules) }}
      fail-fast: false # 一个失败不影响其他
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7

      - name: 获取出站配置
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 60
          warning_on_retry: true
          command: |
            uv run --no-dev -m proxy.${{ matrix.module }}

      - name: 上传结果
        uses: actions/upload-artifact@v7
        with:
          name: result-${{ matrix.module }}
          path: result.json

  pack:
    needs: get_outbounds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7

      - name: 下载结果
        uses: actions/download-artifact@v8
        with:
          path: results

      - name: 下载GeoIP数据库
        run: wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb -O Country.mmdb

      - name: 运行程序
        run: |
          uv run --no-dev -m proxy
        env:
          JEGOCLOUD_USERNAME: ${{ secrets.JEGOCLOUD_USERNAME }}
          JEGOCLOUD_PASSWORD: ${{ secrets.JEGOCLOUD_PASSWORD }}

      - name: 获取日期
        run: |
          echo "TITLE=$(date +'%Y年%m月%d日')" >> $GITHUB_ENV
          echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 创建发行版
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          name: ${{ env.TITLE }}
          tag_name: ${{ env.TAG }}
          files: result.json
          body_path: ./release_notes.md
