name: 自动更新

on:
    schedule:
        - cron: "45 2 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v6
            - uses: astral-sh/setup-uv@v7

            - name: 初始化
              run: |
                  mkdir -p results
                  wget -q https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb -O Country.mmdb
                  echo $GITHUB_TOKEN | gh auth login --with-token
                  uv sync --no-dev

            - name: 获取节点
              env:
                  JEGOCLOUD_USERNAME: ${{ secrets.JEGOCLOUD_USERNAME }}
                  JEGOCLOUD_PASSWORD: ${{ secrets.JEGOCLOUD_PASSWORD }}
              run: |
                  for mod in ./src/proxy/*/; do
                      name=$(basename "$mod")
                      echo "▶️ $name"
                      uv run --no-dev -m proxy."$name" && mv result.json "results/${name}.json" || true
                  done

            - name: 合并结果
              run: uv run --no-dev -m proxy

            - name: 发布
              run: |
                  TAG=$(date +'%Y-%m-%d')
                  TITLE=$(date +'%Y年%m月%d日')
                  gh release create "$TAG" --title "$TITLE" --notes-file ./release_notes.md result.json
